import { NextRequest, NextResponse } from 'next/server';
import { validateLayoutConfig } from '@ouas/validator';
import { saveConfig, getCurrentConfig, restorePreviousConfig, clearConfigHistory } from '@/lib/store';
import { presetConfigs } from '@/data/mock-data';
import manifestData from '@/data/manifest.ouas.json';
import type { Manifest, LayoutConfig } from '@ouas/validator';

const manifest = manifestData as unknown as Manifest;

// Call this at the top of every POST and DELETE handler
function enforceOwnership(
  req: NextRequest,
  paramUserId: string
): NextResponse | null {
  const requestingUserId = req.headers.get("x-user-id");

  if (!requestingUserId) {
    return NextResponse.json(
      { error: "Authentication required." },
      { status: 401 }
    );
  }

  if (requestingUserId !== paramUserId) {
    // Return 403, never 404 — don't leak whether the user ID exists
    return NextResponse.json(
      { error: "You are not authorised to modify this user's config." },
      { status: 403 }
    );
  }

  return null; // null means ownership check passed
}

// GET — return current config
export async function GET(
  req: NextRequest,
  { params }: { params: Promise<{ userId: string }> }
) {
  const resolvedParams = await params;
  const userId = resolvedParams.userId;
  
  if (!userId) {
    return NextResponse.json({ error: 'Missing userId' }, { status: 400 });
  }

  // Check if we have a custom config generated by the agent
  const customConfig = getCurrentConfig(userId);
  if (customConfig) {
    return NextResponse.json(customConfig, {
      headers: { 'X-OUAS-Config-Source': 'custom' }
    });
  }

  // Check if it's one of our hardcoded mock users that have presets
  let presetKey: string | null = null;
  if (userId === 'user_exec_001') presetKey = 'executive';
  if (userId === 'user_student_001') presetKey = 'student';
  if (userId === 'user_researcher_001') presetKey = 'researcher';

  if (presetKey && presetConfigs[presetKey]) {
    return NextResponse.json(presetConfigs[presetKey], {
      headers: { 'X-OUAS-Config-Source': 'default' }
    });
  }

  // If no config found, return 404 (Renderer will use default layout)
  return NextResponse.json({ error: 'No config found' }, { status: 404 });
}

// POST — save new config (after validation)
export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ userId: string }> }
) {
  const resolvedParams = await params;
  const userId = resolvedParams.userId;

  const ownershipError = enforceOwnership(req, userId);
  if (ownershipError) return ownershipError;

  // Reject configs over 4KB at the API layer before validator even runs
  const contentLength = Number(req.headers.get("content-length") ?? 0);
  if (contentLength > 4096) {
    return NextResponse.json(
      { error: "Config payload exceeds 4KB limit.", code: "CONFIG_TOO_LARGE" },
      { status: 413 }
    );
  }

  const body = await req.text();
  const validation = validateLayoutConfig(body, manifest);

  if (!validation.valid) {
    return NextResponse.json(
      { valid: false, errors: validation.errors },
      { status: 422 }
    );
  }

  const config = JSON.parse(body) as LayoutConfig;
  saveConfig(userId, config);

  return NextResponse.json({ valid: true, configId: config.config_id });
}

// DELETE — restore previous config, not wipe to default
export async function DELETE(
  req: NextRequest,
  { params }: { params: Promise<{ userId: string }> }
) {
  const resolvedParams = await params;
  const userId = resolvedParams.userId;

  const ownershipError = enforceOwnership(req, userId);
  if (ownershipError) return ownershipError;

  const previous = restorePreviousConfig(userId);

  if (!previous) {
    // No history — wipe to default
    clearConfigHistory(userId);
    return NextResponse.json({ restored: false, message: "Reset to default layout." });
  }

  return NextResponse.json({
    restored: true,
    config: previous,
    message: "Restored previous layout."
  });
}
